In [ ]:
import numpy as np

Q-1

In [ ]:
def no_zeros(arrayInput):
    for i in arrayInput:
        print("false")
        break
    else:
        print("true")
    print(arrayInput)

x=np.random.randint(-3,3,size=(4))
print(no_zeros(x))
   


Q-2

In [ ]:
def linearly_distributed(n, min, max):
    if n <= 0:
        raise ValueError("Number of elements (n) should be greater than 0.")
    
    if min >= max:
        raise ValueError("min_val should be less than max val.")

    # Use numpy's linspace to create equally spaced elements
    result = np.linspace(min, max - (max - min) / n, n)

    return result

max=int(input("Enter the max range "))
min=int(input("Enter the min range "))
n=int(input("Enter the length of array "))
final = linearly_distributed(n,min, max)
print(final)



Q - 3

In [ ]:
def two_dimensions(n):
    
    border_array = np.ones((n, n), dtype=int)
    border_array[1:-1, 1:-1] = 0
    return border_array

n = int(input("The size of 2d Array: "))
result = two_dimensions(n)
print(result)
    

    

Q-4

In [ ]:
def create_array(n,min,max):
    x=np.random.randint(min,max,size=(n))
    return x
   

max=int(input("Enter the max range "))
min=int(input("Enter the min range "))
n=int(input("Enter the length of array "))
print('The generated array is ',create_array(n,min,max))

Q-5

In [31]:
def random_generation(n,min,max):
    
    if n * n > max - min + 1:
        raise ValueError("The range of values (max - min + 1) should be greater than or equal to n*n.")

    # Create an initial array with unique values
    unique_values = np.arange(min, max + 1)

    # Shuffle the array randomly
    np.random.shuffle(unique_values)

    # Reshape the shuffled array into an n x n matrix
    result = unique_values[:n * n].reshape((n, n))

    return result

# Example usage:
max=int(input("Enter the max range "))
min=int(input("Enter the min range "))
n=int(input("Enter the length of array "))
random_array = random_generation(n, min, max)
print(random_array)


[[ 7  3 10]
 [ 4  9  8]
 [ 6  2  5]]
